# Generated by Django 5.2.1 on 2025-06-16 02:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="PaymentHistory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("imp_uid", models.CharField(max_length=255, unique=True)),
                ("merchant_uid", models.CharField(max_length=100)),
                ("amount", models.PositiveIntegerField()),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("paid", "paid"),
                            ("cancelled", "cancelled"),
                            ("failed", "failed"),
                        ],
                        max_length=20,
                    ),
                ),
                ("payment_method", models.CharField(max_length=50, null=True)),
                ("card_name", models.CharField(max_length=100, null=True)),
                ("card_number", models.CharField(max_length=50, null=True)),
                ("paid_at", models.DateTimeField(null=True)),
                ("receipt_url", models.URLField(max_length=500, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_delete", models.BooleanField(default=False, verbose_name="삭제 여부")),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="payment_histories",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "결제 이력",
                "verbose_name_plural": "결제 이력 목록",
                "db_table": "payment_histories",
                "ordering": ["-created_at"],
            },
        ),
    ]
