# Generated by Django 5.2.1 on 2025-06-13 10:47

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("paymenthistory", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="paymenthistory",
            name="is_delete",
            field=models.BooleanField(default=False, verbose_name="삭제 여부"),
        ),
    ]
