# Generated by Django 5.2.1 on 2025-06-13 06:55

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("route", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="route",
            name="like_count",
            field=models.PositiveIntegerField(default=0, verbose_name="경로 좋아요 수"),
        ),
    ]
