[tool.poetry]
name = "localstorymap"
version = "0.1.0"
description = ""
authors = ["Alex424525 <sht914@gmail.com>"]

[tool.poetry.dependencies]
python = "^3.13"
django = "^5.2.1"
psycopg2-binary = "^2.9.10"
python-dotenv = "^1.1.0"
djangorestframework = "^3.16.0"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
