# Generated by Django 5.2.1 on 2025-06-10 05:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("marker", "0001_initial"),
        ("route", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="RouteMarker",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "sequence",
                    models.PositiveIntegerField(
                        help_text="경로 내에서의 마커 순서 (1부터 시작)", verbose_name="순서"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="연결일시"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="수정일시"),
                ),
                (
                    "marker",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="route_markers",
                        to="marker.marker",
                        verbose_name="마커",
                    ),
                ),
                (
                    "route",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="route_markers",
                        to="route.route",
                        verbose_name="경로",
                    ),
                ),
            ],
            options={
                "verbose_name": "경로-마커 연결",
                "verbose_name_plural": "경로-마커 연결들",
                "db_table": "route_markers",
                "ordering": ["route", "sequence"],
                "unique_together": {("route", "marker"), ("route", "sequence")},
            },
        ),
    ]
