# Generated by Django 5.2.1 on 2025-06-14 08:09

from django.db import migrations, models

import apps.users.models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0002_alter_user_profile_image"),
    ]

    operations = [
        migrations.AlterModelManagers(
            name="user",
            managers=[
                ("objects", apps.users.models.CustomUserManager()),
            ],
        ),
        migrations.RemoveField(
            model_name="user",
            name="username",
        ),
        migrations.AlterField(
            model_name="user",
            name="social_id",
            field=models.CharField(
                blank=True,
                help_text="카카오/구글에서 제공받은 유저 고유 ID",
                max_length=100,
                null=True,
                verbose_name="소셜 고유 ID",
            ),
        ),
    ]
