# Generated by Django 5.2.1 on 2025-06-14 08:16

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0003_alter_user_managers_remove_user_username_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="is_paid_user",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="user",
            name="nickname",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name="user",
            name="profile_image",
            field=models.ImageField(blank=True, null=True, upload_to="profile_images/"),
        ),
        migrations.AlterField(
            model_name="user",
            name="provider",
            field=models.CharField(
                choices=[("kakao", "Kakao"), ("google", "Google")],
                default="kakao",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="social_id",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
