# Generated by Django 5.2.1 on 2025-06-16 09:18

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0004_alter_user_is_paid_user_alter_user_nickname_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="nickname",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name="user",
            name="social_id",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
