# Generated by Django 5.2.1 on 2025-06-16 09:30

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0005_alter_user_nickname_alter_user_social_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="profile_image",
            field=models.ImageField(
                blank=True, max_length=300, null=True, upload_to="profile_images/"
            ),
        ),
    ]
