# Generated by Django 5.2.1 on 2025-06-20 04:34

import storages.backends.s3
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0006_alter_user_nickname_alter_user_profile_image_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="profile_image",
            field=models.ImageField(
                blank=True,
                max_length=300,
                null=True,
                storage=storages.backends.s3.S3Storage(),
                upload_to="profile_images/%Y/%m/%d/",
            ),
        ),
    ]
