# Generated by Django 5.2.1 on 2025-06-17 07:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("story", "0001_initial"),
        ("storyimage", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="storyimage",
            name="story",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="storyimages",
                to="story.story",
            ),
        ),
        migrations.DeleteModel(
            name="Story",
        ),
    ]
