# Generated by Django 5.2.1 on 2025-06-20 04:07

import storages.backends.s3
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("storyimage", "0003_storyimage_user"),
    ]

    operations = [
        migrations.AlterField(
            model_name="storyimage",
            name="image_file",
            field=models.ImageField(
                storage=storages.backends.s3.S3Storage(),
                upload_to="story_images/%Y/%m/%d/",
            ),
        ),
    ]
