# Generated by Django 5.2.1 on 2025-06-19 14:51

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("ai_service", "0001_initial"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Location",
        ),
    ]
