# Generated by Django 5.2.1 on 2025-06-18 02:43

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("story", "0002_storycomment_like_count_alter_storycomment_content"),
    ]

    operations = [
        migrations.AlterField(
            model_name="story",
            name="emoji",
            field=models.CharField(
                blank=True, max_length=500, verbose_name="스토리 감정 이모티콘"
            ),
        ),
    ]
