# Generated by Django 5.2.1 on 2025-06-19 15:34

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("story", "0003_alter_story_emoji"),
    ]

    operations = [
        migrations.AddField(
            model_name="commentlike",
            name="like_count",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="storylike",
            name="like_count",
            field=models.PositiveIntegerField(default=0),
        ),
    ]
