# Generated by Django 5.2.1 on 2025-06-10 05:20

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Marker",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("marker_name", models.CharField(max_length=100, verbose_name="마커명")),
                ("adress", models.TextField(verbose_name="도로명주소 or 지번주소")),
                (
                    "description",
                    models.TextField(blank=True, null=True, verbose_name="마커 설명"),
                ),
                (
                    "image",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="markers/",
                        verbose_name="마커 이미지",
                    ),
                ),
                (
                    "latitude",
                    models.DecimalField(
                        decimal_places=7, max_digits=10, verbose_name="위도"
                    ),
                ),
                (
                    "longitude",
                    models.DecimalField(
                        decimal_places=7, max_digits=10, verbose_name="경도"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="생성일시"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="수정일시"),
                ),
            ],
            options={
                "verbose_name": "마커",
                "verbose_name_plural": "마커들",
                "db_table": "markers",
                "ordering": ["-created_at"],
            },
        ),
    ]
