# Generated by Django 5.2.1 on 2025-06-10 06:35

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("marker", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="marker",
            name="adress",
            field=models.TextField(blank=True, null=True, verbose_name="도로명주소 or 지번주소"),
        ),
    ]
