# Generated by Django 5.2.1 on 2025-06-13 06:55

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("marker", "0002_alter_marker_adress"),
    ]

    operations = [
        migrations.AddField(
            model_name="marker",
            name="layer",
            field=models.CharField(
                choices=[("tour", "관광명소"), ("food", "맛집"), ("cafe", "카페")],
                default="tour",
                max_length=20,
                verbose_name="레이어",
            ),
        ),
    ]
