# Generated by Django 5.2.1 on 2025-06-13 07:02

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("marker", "0003_marker_layer"),
    ]

    operations = [
        migrations.AlterField(
            model_name="marker",
            name="layer",
            field=models.CharField(
                blank=True,
                choices=[("tour", "관광명소"), ("food", "맛집"), ("cafe", "카페")],
                max_length=20,
                null=True,
                verbose_name="레이어",
            ),
        ),
    ]
