# Generated by Django 5.2.1 on 2025-06-17 02:17

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("marker", "0004_alter_marker_layer"),
    ]

    operations = [
        migrations.AddField(
            model_name="marker",
            name="like_count",
            field=models.PositiveIntegerField(default=0, verbose_name="마커 좋아요 수"),
        ),
    ]
