# Generated by Django 5.2.1 on 2025-06-18 04:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("marker", "0005_marker_like_count"),
        ("story", "0002_storycomment_like_count_alter_storycomment_content"),
    ]

    operations = [
        migrations.AddField(
            model_name="marker",
            name="story",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="stories",
                to="story.story",
            ),
        ),
        migrations.AlterField(
            model_name="marker",
            name="layer",
            field=models.CharField(
                blank=True,
                choices=[("tour", "관광명소"), ("food", "맛집"), ("infra", "인프라")],
                max_length=20,
                null=True,
                verbose_name="레이어",
            ),
        ),
    ]
