# Generated by Django 5.2.1 on 2025-06-19 14:24

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("marker", "0006_marker_story_alter_marker_layer"),
    ]

    operations = [
        migrations.AddField(
            model_name="marker",
            name="summary_text",
            field=models.TextField(blank=True, null=True, verbose_name="요약문"),
        ),
    ]
