# Generated by Django 5.2.1 on 2025-06-20 04:18

import storages.backends.s3
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("marker", "0007_marker_summary_text"),
    ]

    operations = [
        migrations.AlterField(
            model_name="marker",
            name="image",
            field=models.ImageField(
                blank=True,
                null=True,
                storage=storages.backends.s3.S3Storage(),
                upload_to="markers/",
                verbose_name="마커 이미지",
            ),
        ),
    ]
