# Generated by Django 5.2.1 on 2025-06-24 02:00

from django.db import migrations, models

import apps.marker.models


class Migration(migrations.Migration):
    dependencies = [
        ("marker", "0008_alter_marker_image"),
    ]

    operations = [
        migrations.AlterField(
            model_name="marker",
            name="image",
            field=models.ImageField(
                blank=True,
                null=True,
                storage=apps.marker.models.select_marker_storage,
                upload_to="markers/",
                verbose_name="마커 이미지",
            ),
        ),
    ]
